version: '3'

services:
  app:
    image: vtk-api
    container_name: vtk-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - USER_DIR=/app
      - STATIC_PATH=/app/static/
      - DB_NAME=mydb.sqlite
      - DB_USER=admin
      - DB_PASSWORD=admin
    volumes:
      - static-files:/app/static
volumes:
    static-files: